-keep class com.ryanheise.** { *; }
-dontwarn com.ryanheise.**
-keep class androidx.media3.** { *; }
-dontwarn androidx.media3.**
-keep class com.google.android.exoplayer2.** { *; }
-dontwarn com.google.android.exoplayer2.**
-keep class com.google.android.gms.** { *; }
-dontwarn com.google.android.gms.**
